[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

# See more config options at https://book.getfoundry.sh/reference/config/solidity-compiler

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
